import React, { ReactNode } from "react";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import NavBar from "./../components/navBar";
import { Providers } from "./GlobalRedux/provider";
import Notification from "../components/Notifications"
import 'react-toastify/dist/ReactToastify.css'
import ThemeMode from "../components/ThemeMode"


const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Education Platform",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {

  return (
    <html suppressHydrationWarning={true} lang="en">
      <head>
        <title>Education Platform</title>
        <meta name="description" content="Education Platform" />
        <link rel="icon" type="image/x-icon" href="/images/Login.png" />
      </head>
      <body >

        <Providers>
          <ThemeMode >
            <NavBar />
            <Notification />
            {children}
          </ThemeMode>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
